CREATE TABLE leave_submission_lock (
    staff_member_id VARCHAR(100) PRIMARY KEY
);

CREATE TABLE leave_request (
    id VARCHAR(36) PRIMARY KEY,
    staff_member_id VARCHAR(100) NOT NULL,
    manager_id VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR(500) NOT NULL,
    leave_type VARCHAR(30) NOT NULL,
    day_portion VARCHAR(20) NOT NULL,
    charged_leave_days DECIMAL(5,1) NOT NULL,
    status VARCHAR(30) NOT NULL,
    decision_comment VARCHAR(500),
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT chk_leave_request_dates CHECK (end_date >= start_date)
);

CREATE TABLE leave_allowance (
    id VARCHAR(36) PRIMARY KEY,
    staff_member_id VARCHAR(100) NOT NULL,
    first_name VARCHAR(20) NOT NULL,
    surname VARCHAR(20) NOT NULL,
    manager_id VARCHAR(100) NOT NULL,
    business_year_start DATE NOT NULL,
    business_year_end DATE NOT NULL,
    base_entitlement DECIMAL(5,1) NOT NULL,
    carried_over_days DECIMAL(5,1) DEFAULT 0.0 NOT NULL,
    remaining_days DECIMAL(5,1) NOT NULL,
    version BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT uq_leave_allowance_staff_business_year
        UNIQUE (staff_member_id, business_year_start, business_year_end),
    CONSTRAINT chk_leave_allowance_business_year
        CHECK (business_year_end >= business_year_start),
    CONSTRAINT chk_leave_allowance_base_entitlement CHECK (base_entitlement >= 0),
    CONSTRAINT chk_leave_allowance_carry_over
        CHECK (carried_over_days >= 0 AND carried_over_days <= 5.0),
    CONSTRAINT chk_leave_allowance_remaining_non_negative CHECK (remaining_days >= 0),
    CONSTRAINT chk_leave_allowance_remaining_within_entitlement
        CHECK (remaining_days <= base_entitlement + carried_over_days)
);

CREATE TABLE leave_allowance_carry_over (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_member_id VARCHAR(100) NOT NULL,
    source_allowance_id VARCHAR(36) NOT NULL,
    target_allowance_id VARCHAR(36) NOT NULL,
    carried_days DECIMAL(5,1) NOT NULL,
    applied_on DATE NOT NULL,
    CONSTRAINT uq_leave_allowance_carry_source_target
        UNIQUE (source_allowance_id, target_allowance_id),
    CONSTRAINT chk_leave_allowance_carried_days
        CHECK (carried_days >= 0 AND carried_days <= 5.0)
);

CREATE TABLE public_holiday (
    holiday_date DATE PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE leave_request_event_stream (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id VARCHAR(36) NOT NULL,
    sequence_number BIGINT NOT NULL,
    event_type VARCHAR(150) NOT NULL,
    event_body VARCHAR(65000) NOT NULL,
    occurred_on DATE NOT NULL,
    CONSTRAINT uq_leave_request_stream_sequence
        UNIQUE (aggregate_id, sequence_number)
);

CREATE INDEX idx_leave_request_stream_aggregate_sequence
    ON leave_request_event_stream (aggregate_id, sequence_number);

CREATE TABLE staff_member (
    id VARCHAR(36) PRIMARY KEY,
    first_name VARCHAR(20) NOT NULL,
    surname VARCHAR(20) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    hire_date DATE NOT NULL,
    department VARCHAR(100) NOT NULL,
    manager_id VARCHAR(36) NOT NULL,
    job_role VARCHAR(100) NOT NULL,
    role_start_date DATE NOT NULL,
    job_level VARCHAR(50) NOT NULL,
    employment_type VARCHAR(50) NOT NULL,
    employment_status VARCHAR(30) NOT NULL,
    CONSTRAINT chk_staff_member_role_start CHECK (role_start_date >= hire_date)
);

CREATE TABLE staff_hr_event_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_id BIGINT NOT NULL,
    event_type VARCHAR(150) NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_staff_hr_event_receipt_source_type
        UNIQUE (source_event_id, event_type)
);

CREATE TABLE event_store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_on DATE NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    event_body VARCHAR(65000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    retry_count INT DEFAULT 0 NOT NULL,
    CONSTRAINT chk_event_store_retry_count CHECK (retry_count >= 0),
    CONSTRAINT chk_event_store_status CHECK (
        status IN ('LOCAL', 'PENDING', 'PUBLISHED', 'FAILED', 'UNROUTABLE')
    )
);

CREATE TABLE event_publication (
    id UUID NOT NULL PRIMARY KEY,
    completion_date TIMESTAMP(9) WITH TIME ZONE,
    event_type VARCHAR(512) NOT NULL,
    listener_id VARCHAR(512) NOT NULL,
    publication_date TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    serialized_event VARCHAR(4000) NOT NULL,
    status VARCHAR(20),
    completion_attempts INT,
    last_resubmission_date TIMESTAMP(9) WITH TIME ZONE
);

CREATE INDEX event_publication_by_listener_and_event_idx
    ON event_publication (listener_id, serialized_event);

CREATE INDEX event_publication_by_completion_date_idx
    ON event_publication (completion_date);

CREATE TABLE notification (
    id VARCHAR(36) PRIMARY KEY,
    source_event_id BIGINT NOT NULL UNIQUE,
    recipient_id VARCHAR(36) NOT NULL,
    leave_request_id VARCHAR(36) NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    message VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE leave_reporting_projection (
    leave_request_id VARCHAR(36) PRIMARY KEY,
    source_event_id BIGINT NOT NULL UNIQUE,
    staff_member_id VARCHAR(100) NOT NULL,
    leave_type VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    day_portion VARCHAR(20) NOT NULL,
    charged_leave_days DECIMAL(5,1) NOT NULL,
    status VARCHAR(30) NOT NULL,
    occurred_on DATE NOT NULL,
    CONSTRAINT chk_leave_reporting_dates CHECK (end_date >= start_date)
);

CREATE TABLE leave_audit (
    source_event_id BIGINT PRIMARY KEY,
    leave_request_id VARCHAR(36) NOT NULL,
    staff_member_id VARCHAR(100) NOT NULL,
    action VARCHAR(40) NOT NULL,
    previous_status VARCHAR(30),
    new_status VARCHAR(30) NOT NULL,
    decision_comment VARCHAR(500),
    occurred_on DATE NOT NULL
);

CREATE INDEX idx_leave_audit_request_event
    ON leave_audit (leave_request_id, source_event_id);

CREATE INDEX idx_leave_audit_staff_event
    ON leave_audit (staff_member_id, source_event_id);

CREATE TABLE hr_absence_sync (
    source_event_id BIGINT PRIMARY KEY,
    leave_request_id VARCHAR(36) NOT NULL,
    staff_member_id VARCHAR(100) NOT NULL,
    sync_action VARCHAR(40) NOT NULL,
    leave_type VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    day_portion VARCHAR(20) NOT NULL,
    charged_leave_days DECIMAL(5,1) NOT NULL,
    status VARCHAR(30) NOT NULL,
    occurred_on DATE NOT NULL,
    CONSTRAINT chk_hr_absence_sync_dates CHECK (end_date >= start_date),
    CONSTRAINT chk_hr_absence_sync_charge CHECK (charged_leave_days >= 0)
);

CREATE INDEX idx_hr_absence_sync_staff_event
    ON hr_absence_sync (staff_member_id, source_event_id);
